first2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reestr/', include('reestr.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reestr/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'reestr'

urlpatterns = [
    #/reestr/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /reestr/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /reestr/album/2/update
    url(r'^(?P<pk>[0-9]+)/update/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /reestr/album/2/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # /reestr/export/xls
    url(r'export/xls/$', views.export_users_xls, name='export_reestr_xls'),

    # /reestr/irpin
    url(r'irpin/$', views.IrpinView.as_view(), name='irpin'),
]

reestr/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse




class Album(models.Model):
    # Choices
    STREET_TYPE = (
        ("вул.Шевченка", "вул.Шевченка"),
        ("вул.Садова", "вул.Садова"),
        ("вул.Тургенівська", "вул.Тургенівська"),
        ("вул.Університетська", "вул.Університетська"),
    )
    # Choices
    ADDRESS_TYPE = (
        ("м.Ірпінь", "м.Ірпінь"),
    )
    # Condition
    CONDITION_TYPE = (
        ("Реєстрація", "Реєстрація"),
        ("Зняття з реєстрації", "Зняття з реєстрації")
    )
    first_name = models.CharField("Прізвище", max_length=250, default='')
    middle_name = models.CharField("Ім’я", max_length=250, default='')
    last_name = models.CharField("По батькові",max_length=500, default='')
    date_of_birht = models.CharField("Дата народження",max_length=100, default='')
    place_of_birth = models.TextField("Місце народження", default='')
    address = models.CharField("Місце проживання", max_length=250, choices=ADDRESS_TYPE, default='')
    street = models.CharField("Вулиця",max_length=500, choices=STREET_TYPE, default='')
    house = models.CharField("Будинок",max_length=500, default='')
    date_of_entry = models.CharField("Дата реєстр./зняття", max_length=250, default='')
    condition = models.CharField("Дія", max_length=500, choices=CONDITION_TYPE, default='')
    type_doc = models.CharField("Тип документа", max_length=250, default='')
    seria_doc = models.CharField("Серія документа", max_length=250, default='')
    number_doc = models.CharField("Номер документа", max_length=250, default='')
    date_doc = models.CharField("Дата видачі", max_length=250, default='')
    subject_doc = models.CharField("Суб’єкт, що видав", max_length=250, default='')
    whence_came = models.CharField("Звідки прибув", max_length=250, default='')
    document = models.FileField("Додати документ",)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'Person'

    import sys
    reload(sys)
    sys.setdefaultencoding('utf-8')
    def get_absolute_url(self):
        return reverse('reestr:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.first_name + ' - ' + self.middle_name + ' - ' + self.last_name


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

reestr/views.py
# -*- coding: utf-8 -*-
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album
from django.http import HttpResponse
import xlwt


class IndexView(generic .ListView):
    template_name = 'reestr/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic .DetailView):
    model = Album
    template_name = 'reestr/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['first_name', 'middle_name', 'last_name', 'date_of_birht', 'place_of_birth',
              'address', 'street', 'house', 'date_of_entry', 'condition',
              'type_doc', 'seria_doc', 'number_doc', 'date_doc', 'subject_doc', 'whence_came', 'document']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['first_name', 'middle_name', 'last_name', 'date_of_birht', 'place_of_birth',
              'address', 'street', 'house', 'date_of_entry', 'condition',
              'type_doc', 'seria_doc', 'number_doc', 'date_doc', 'subject_doc', 'whence_came', 'document']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('reestr:index')

class IrpinView(generic .TemplateView):
    template_name = 'reestr/irpin.html'
    model = Album

def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="reestr.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Reestr')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Прізвище', 'Ім’я', 'По батькові', 'Дата народження', 'Місце народження', 'Адреса', 'Вулиця',
               'Будинок', 'Дата реєстрації', 'Дія',
               'Тип документа', 'Серія', 'Номер документа', 'Дата видачі', 'Суб’єкт, що видав', 'Звідки прибув' ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Album.objects.all().values_list('first_name', 'middle_name', 'last_name', 'date_of_birht',
                                           'place_of_birth', 'address', 'street', 'house', 'date_of_entry', 'condition',
                                           'type_doc', 'seria_doc', 'number_doc', 'date_doc', 'subject_doc', 'whence_came',)
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response

reestr/templates/reestr/album_form.html
{% extends 'reestr/base.html' %}
{% block tittle %} Додати запис{% endblock %}
{% block albums_active %} active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row" >
        <div class="col -sm-12 col-md-10">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'reestr/form-template.html' %}
                        <style type="text/css">
select {
    width: 30%;
    padding: 8px 10px;
    border: none;
    border-radius: 4px;
    background-color: #e5e5e5;
}

#id_subject_doc {
    width: 450px;
    height: 30px;
}
#id_whence_came {
    width: 450px;
    height: 30px;
}
#id_number_doc {
    width: 100px;
}
#id_date_doc {
    width: 100px;
}
            </style>
                    <div class="form-group">

                        <div class="col-xs-6 col-sm-3">
                                <button type="submit" class="btn btn-success">Додати запис</button>
                        </div>
                        <div class="col-xs-6 col-sm-3">
                                <input type="button" value="Повернутися" class="btn btn-primary" onclick="history.back()">
                        </div>
                    </div>
                    </form>
                 </div>
             </div>
        </div>

    </div>
</div>
{% endblock %}

reestr/templates/reestr/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %}Ірпінь {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'reestr/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'reestr:irpin' %}">Ірпінь</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
            <li class="active">
            </li>
            </ul>
<ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'reestr:index' %}">
                    <span class="glyphicon glyphicon-user"</span>
                    </span>&nbsp; Список громадян</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Пошук</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'reestr:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Додати запис
                    </a>

                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Вийти
                    </a>
                 </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

reestr/templates/reestr/detail.html
{% extends 'reestr/base.html' %}
{% block tittle %} Детальна інформація {% endblock %}

{% block body %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'reestr/style.css' %}" />

        <p class="lead"><strong>Детально:</strong></p>

      <table class="table table-hover table table-striped " border="2" width="100%" cellspacing="1">
           <style>
           th {
        text-align: center; /* Выравниваем текст по центру ячейки для тега th */
       }
           </style>
       <tr>
         <th align="center" > ПІБ </th>
         <th align="center" >Дата народження </th>
         <th align="center" >Місце народження </th>
         <th align="center" >Місце проживання </th>
         <th align="center" >Вулиця </th>
         <th align="center" >Будинок </th>
         <th align="center" >Дата реєстрації </th>
         <th align="center" >Дія </th>
       </tr>
       <tr>
           <style>
           td {
        text-align: center; /* Выравниваем текст по центру ячейки для тега td */
       }
           </style>
        <td>{{ album.first_name }} {{ album.middle_name }} {{ album.last_name }}</td>
        <td>{{ album.date_of_birht }} </td>
        <td>{{ album.place_of_birth }} </td>
        <td>{{ album.address }} </td>
        <td>{{ album.street }} </td>
        <td>{{ album.house }} </td>
        <td>{{ album.date_of_entry }} </td>
        <td>{{ album.condition }} </td>

      </tr>
      </table>
    <br>
    <h5><p class="text-primary"><strong>Документи заявника та звідки прибув:</strong></p></h5>
    <table class="table table-hover table table-striped " border="2" width="100%" cellspacing="1" style="width: 850px;">

       <tr>
         <th align="center" >Тип документа </th>
         <th align="center" >Серія </th>
         <th align="center" >Номер документа </th>
         <th align="center" >Дата видачі </th>
         <th align="center" >Суб’єкт, що видав </th>
         <th align="center" >Звідки прибув </th>
       </tr>
       <tr>
           <style>
           td {
        text-align: center; /* Выравниваем текст по центру ячейки */
       }
           </style>
        <td>{{ album.type_doc }} </td>
        <td>{{ album.seria_doc }} </td>
        <td>{{ album.number_doc }} </td>
        <td>{{ album.date_doc }} </td>
        <td>{{ album.subject_doc }} </td>
        <td>{{ album.whence_came }} </td>

      </tr>
      </table>
      <p>
      <p>
    <p class="text-info"><b>Додані документи:</b></p>
        <td><iframe src="{{ album.document.url }}"width="850" height="320"></iframe></td>
      <p>
      <p>
<!-- Delete Person -->
                            <form action="{% url 'reestr:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="submit" value="Видалити" class="btn btn-danger"  name="album_id" value="{{ album.id }}">
                            </form>
<!-- Update Person -->
                            <form action="{% url 'reestr:album-update' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="submit" value="Редагувати" class="btn btn-warning"  name="album_id" value="{{ album.id }}">
                            </form>
     <style>
     p {
    text-indent: 20px; /* Отступ первой строки в пикселах */
     }
     </style>
     <input type="button" value="Повернутися" class="btn btn-primary" onclick="history.back()">
    <a href="#" onclick="showFun()"><strong>Картка реєстрації особи</strong><span class="glyphicon glyphicon-file" </span>
    <span class="glyphicon glyphicon-menu-down"</span></a>
    <ul>
    </ul>


 <br>
     <br>
<script type="text/javascript">
var visible = true;
function showFun() {
    if(visible) {
        document.getElementById('myShowBlock' ).style.display = 'block';
        visible = false;
    } else {
        document.getElementById('myShowBlock' ).style.display = 'none';
        visible = true;
    }
}
</script>
      <style>
   .kartka {
    margin-right: 52%; /* Отступ справа */
    margin-left: 2%; /* Отступ слева */
    margin-bottom: 2%; /* Отступ слева */
    background: #fcfcfc; /* Цвет фона */
   }
  </style>

<div class="kartka" id="myShowBlock" style="display:none;><p class="lead"><strong>Картка реєстрації особи</strong></p>
       <br>1. Прізвище: <b>{{ album.first_name }}</b>
       <br>2. Ім’я: <b>{{ album.middle_name }}</b>
       <br>3. По батькові: <b>{{ album.last_name }}</b>
       <br>
       <br>4. Попереднє прізвище, ім’я, по батькові (за наявності):__________
       <br>5. Дата народження: <b>{{ album.date_of_birht }}</b>
       <br>6. Громадянство, підданство (за наявності):__________
       <br>
       <br>
    <table width="550" border="1">
   <tr>
      <td>7. Місце народження:</td>
      <td colspan="3"><b>{{ album.place_of_birth }}</b></td>
   </tr>
   <tr>
      <td>8. Коли і звідки прибув:</td>
      <td><b>{{ album.whence_came }}</b></td>
      <td colspan="2">9.Переїхав у межах адміністративно-територіальної одиниці з вул.:
          ____________________
          ____________________</td>
   </tr>
       <tr>
       <td>10. Паспортний документ (тип):</td>
       <td>Серія</td>
       <td>Номер</td>
       <td>Ким і коли виданий:</td>
   </tr>
       </tr>
       <tr>
       <td><b>{{ album.type_doc }}</b></td>
       <td><b>{{ album.seria_doc }}</b></td>
       <td><b>{{ album.number_doc }}</b></td>
       <td><b>{{ album.subject_doc }} {{ album.date_doc }}</b></td>
   </tr>
</table>
<br>
<br>
    11. Місце проживання зареєстровано за адресою:
    <br> <b>{{ album.address }} {{ album.street }} {{ album.house }}</b>
    <br>


<br>12. Відомості про реєстрацію місця проживання дітей віком до 14-ти років,
<br>місце проживання яких зареєстроване разом з батьками (прізвище, ім’я,
<br>по батькові, дата та місце народження, дата реєстрації):
<br>________________________________________________________________________
<br>________________________________________________________________________
<br>________________________________________________________________________
<br>
<table width="580" height="400" border="1">
   <tr>
      <td valign="top">13. Штамп реєстрації місця проживання</td>
   </tr>
<br>
   <tr>
      <td valign="top">14. Штамп зняття з реєстрації місця проживання</td>
   </tr>
</table>
</div>

{% endblock %}

reestr/templates/reestr/export.html
<a href="{% url 'export_users_csv' %}">Export all users</a>

reestr/templates/reestr/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="person_title">{{ field.label_tag }}</label>
       <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

reestr/templates/reestr/index.html
{% extends 'reestr/base.html' %}

{% block body %}
{% if all_albums %}

        <h3><span style="border-bottom: medium double teal;">Список територіальної громади м.Ірпінь:</span></h3>
    <ul>
        {% for album in all_albums %}
            <style type="text/css">
  .tdw{
  width:200px;
  }

            </style>
            <table class="table table-hover table table-striped" style="width: 350px;">

            <td style="width: 60px;">

            <a href="/reestr/{{ album.id }}/">{{ album.first_name }} {{ album.middle_name }} {{ album.last_name }} {{ album.date_of_birht }}</a>
             </td>

            </table>
        {% endfor %}
    <p>
<form action="{% url 'reestr:export_reestr_xls' %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="submit" value="Завантажити в Excel" class="btn btn-success">
                            </form>
    </ul>
    {% else %}
    <h3>Немає записів територіальної громади м.Ірпінь </h3>
    {% endif %}
{% endblock %} 

reestr/templates/reestr/irpin.html
{% extends 'reestr/base.html' %}
{% block body %}

      <style>
   .reestrtg {
    text-align:  center;
       font-family: Pompadur, 'Comic Sans MS', cursive;
   }
  </style>
<br>
    <br>
    <br>
    <br>
<div class="reestrtg"><img src="http://127.0.0.1:8000/static/reestr/images/login-sprite.png"/>
<div class="reestrtg" style="color:#101010; font-size:35px"><p>Реєстр територіальної громади м.Ірпінь</p>
</div>
</div>
{% endblock %}